spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://spring-plus.c7u428sau7zx.ap-northeast-2.rds.amazonaws.com:3306/sparta_plus
    username: ${DB_ID}
    password: ${DB_PW}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


cloud:
  aws:
    s3:
      bucket: sparta-image-bucket
      url: https://sparta-image-bucket.s3.ap-northeast-2.amazonaws.com

default-image:
  profile:
    path: https://sparta-image-bucket.s3.ap-northeast-2.amazonaws.com/profile/defaultprofile.jpeg