name: Deploy to EC2
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃 & JDK 설정
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 2. 빌드
      - name: Build JAR
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar

      # 3. SSH 키 작성 및 에이전트 등록
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ec2_key.pem
          chmod 600 ec2_key.pem
          eval "$(ssh-agent -s)"
          ssh-add ec2_key.pem
          ssh-add -l

      # 4. JAR 전송
      - name: Copy JAR to EC2
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no \
            build/libs/*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app.jar

      # 5. 원격 서버에서 앱 실행
      - name: Run JAR on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} <<'EOF'
            pkill -f 'java -jar' || true
            export DB_ID="${DB_ID}"
            export DB_PW="${DB_PW}"
            export JWT_SECRETKEY="${JWT_SECRETKEY}"
            nohup java -jar /home/ubuntu/app.jar --spring.profiles.active=dev > app.log 2>&1 &
          EOF
        env:
          DB_ID:         ${{ secrets.DB_ID }}
          DB_PW:         ${{ secrets.DB_PW }}
          JWT_SECRETKEY: ${{ secrets.JWT_SECRETKEY }}